catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('', views.index, name='index'),
        path('pets/', views.PetListView.as_view(), name='pets'),
        path('pet/<int:pk>', views.PetDetailView.as_view(), name='pet-detail'),
        path('breeders/', views.BreederListView.as_view(), name='breeders'),
        path('breeder/<int:pk>', views.BreederDetailView.as_view(), name='breeder-detail'),

]

petstore/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Animal(models.Model):
    name = models.CharField(max_length=80, null=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name="children")

    class Meta:
        unique_together = ('parent',)
        verbose_name = 'Animal'
        verbose_name_plural = 'Animals'


    def __str__(self):                          
        full_path = [self.name]         
        k = self.parent                          

        while k is not None:
            full_path.append(k.name)
            k = k.parent

        return ' -> '.join(full_path[::-1])


class Pet(models.Model):

    """Model representing a specific pet"""
    id = models.AutoField(primary_key=True)

    # FK used because each pet can only belong to one animal, but each animal may have multiple pets
    animal = models.ForeignKey('Animal', on_delete=models.SET_NULL, null=True, blank=True)

    breeder = models.ForeignKey('Breeder', on_delete=models.SET_NULL, null=True)

    likes = models.TextField(max_length=1000 ,default="", help_text="A few things the pet likes")


    SALE_STATUS = (
        ('a', 'Available'),
        ('u', 'Unavailable'),
        ('r', 'Reserved'),
        ('s', 'Sold'),
    )

    status = models.CharField(
        max_length=1,
        choices=SALE_STATUS,
        blank=True,
        default='a',
        help_text='status of the pet',
    )
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this pet."""
        return reverse('pet-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.id}, {self.animal}'

class Breeder(models.Model):
    """Model representing supplier of the animal"""
    name = models.CharField(max_length=100)
    address = models.TextField(max_length=1000)

    def get_absolute_url(self):
        """Returns the url to access a particular breeder instance."""
        return reverse('breeder-detail', args=[str(self.id)])


    def __str__(self):
        return self.name

catalog/views.py
from django.shortcuts import render
from django.views import generic

from catalog.models import Animal, Pet, Breeder

# Create your views here.

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_animal = Animal.objects.all().count()
    
    # Available (status = 'a')
    pet_available = Pet.objects.filter(status__exact='a').count()
    
    # The 'all()' is implied by default.    
    num_breeder = Breeder.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    
    context = {
        'num_animal': num_animal,
        'num_pet_available': pet_available ,
        'num_breeder': num_breeder,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class PetListView(generic.ListView):
    model = Pet

class PetDetailView(generic.DetailView):
    model = Pet

class BreederListView(generic.ListView):
    model = Breeder

class BreederDetailView(generic.DetailView):
    model = Breeder

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
	  <li><a href="{% url 'pets' %}">All Pets</a></li>
          <li><a href="{% url 'breeders' %}">All Breeders</a></li>
	  {% if user.is_authenticated %}
	  <li>User: {{ user.get_username }}</li>
	  <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
	  {% else %}
	  <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
	  {% endif %} 
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

catalog/templates/catalog/breeder_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ breeder.name }}</h1>

  <p><strong>Address:</strong> {{ breeder.address }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Pets</h4>

<dl>
{% for pet in breeder.pet_set.all %}
  <dt><a href="{% url 'pet-detail' pet.pk %}">{{pet}}</a> ({{pet.all.count}})</dt>
  <dd>{{pet.animal}}</dd>
{% endfor %}
</dl>

  </div>
{% endblock %}

catalog/templates/catalog/breeder_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Breeder List</h1>
  {% if breeder_list %}
  <ul>
    {% for breeder in breeder_list %}
      <li>
        <a href="{{ breeder.get_absolute_url }}">{{ breeder.name }}</a> ({{breeder.address}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no breeders.</p>
  {% endif %}       
{% endblock %}

catalog/templates/catalog/pet_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>ID: {{ pet.id }}</h1>


  <h3>Type: {{ pet.animal }}</h3>
  <h3>Status: {{ pet.get_sale_status_display }}</h3>


  <p><strong>Breeder:</strong> <a href="{% url 'breeder-detail' pet.breeder.pk %}">{{ pet.breeder }}</a></p> 
  <p><strong>Likes:</strong> {{ pet.likes }}</p>
{% endblock %}

catalog/templates/catalog/pet_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Pets</h1>
  {% if pet_list %}
  <ul>
    {% for pet in pet_list %}
      <li>
        <a href="{{ pet.get_absolute_url }}">{{ pet.id }}</a> ({{pet.animal}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no pets</p>
  {% endif %}       
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Mr Jones' Pet Store</h1>
  <p>Welcome to Mr Jones' online pet store</p>
  <h3>The store has the following counts:</h3>
  <ul>
    <li><strong>Animals:</strong> {{ num_animal}}</li>
    <li><strong>Pets:</strong> {{ num_pet_available  }}</li>
    <li><strong>Breeders:</strong> {{ num_breeder }}</li>
  </ul>
  <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}